import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "admin",
      email: "admin@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "user",
      email: "user@gmail.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Noodle",
      request: "populer",
      slug: "noodle",
      category: "food",
      image: "/image/food-1.png",
      price: 25,
      rating: 4.5,
      numReviews: 8,
      desciptions: "Delicious Taste",
      countInStock: 0,
    },
    {
      name: "Cake Bakery",
      request: "non-populer",
      slug: "cake-bakery",
      category: "food",
      image: "/image/food-2.png",
      price: 25,
      rating: 4.5,
      numReviews: 8,
      desciptions: "Delicious Taste",
      countInStock: 10,
    },
    {
      name: "Rice",
      request: "populer",
      slug: "rice",
      category: "food",
      image: "/image/food-3.png",
      price: 25,
      rating: 4.5,
      numReviews: 8,
      desciptions: "Delicious Taste",
      countInStock: 10,
    },
    {
      name: "Thea",
      slug: "thea",
      request: "non-populer",
      category: "Drink",
      image: "/image/drink1.png",
      price: 6,
      rating: 4.5,
      numReviews: 8,
      desciptions: "Delicious Taste",
      countInStock: 10,
    },
    {
      name: "Milk Tea",
      slug: "milk-tea",
      request: "populer",
      category: "Drink",
      image: "/image/drink2.png",
      price: 3,
      rating: 4.5,
      numReviews: 8,
      desciptions: "Delicious Taste",
      countInStock: 0,
    },
    {
      name: "Jus Apple",
      slug: "jus-apple",
      request: "non-populer",
      category: "Drink",
      image: "/image/drink3.png",
      price: 5,
      rating: 4.5,
      numReviews: 8,
      desciptions: "Delicious Taste",
      countInStock: 4,
    },
  ],
};

export default data;
